// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/atoms/color.tsx";
import * as $3 from "./routes/atoms/input.tsx";
import * as $4 from "./routes/atoms/text.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/ColorDisplay.tsx";
import * as $$1 from "./islands/Navigation.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/atoms/color.tsx": $2,
    "./routes/atoms/input.tsx": $3,
    "./routes/atoms/text.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/ColorDisplay.tsx": $$0,
    "./islands/Navigation.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
