// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/atoms/button.tsx";
import * as $2 from "./routes/atoms/input.tsx";
import * as $3 from "./routes/atoms/text.tsx";
import * as $4 from "./routes/atoms/theme.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/particles/color.tsx";
import * as $$0 from "./islands/ColorDisplay.tsx";
import * as $$1 from "./islands/Navigation.tsx";
import * as $$2 from "./islands/ThemeExample.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/atoms/button.tsx": $1,
    "./routes/atoms/input.tsx": $2,
    "./routes/atoms/text.tsx": $3,
    "./routes/atoms/theme.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/particles/color.tsx": $6,
  },
  islands: {
    "./islands/ColorDisplay.tsx": $$0,
    "./islands/Navigation.tsx": $$1,
    "./islands/ThemeExample.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
