export type Colors =
  | 'detergente'
  | 'grafito'
  | 'flan'
  | 'chicle'
  | 'ladrillo'
  | 'arandano'
  | 'jade'
  | 'menta'
  | 'acero'
  | 'arena'
  | 'mantequilla'
  | 'chapopote'
  | 'uva'
  | 'musgo'
  | 'cobalto'
  | 'hielo'
  | 'mota'
  | 'vino'
  | 'blanco'
  | 'ambar'
  | 'lapis'
  | 'marino'
  | 'fresa'
  | 'cedro'
  | 'bombon'
  | 'pulpo'
  | 'tortilla'
  | 'manzana'
  | 'turquesa'
  | 'vinca'
  | 'borrador'
  | 'pitahaya'
  | 'obsidiana'
  | 'kawaii'
  | 'limon'
  | 'pastel'
  | 'papel'
  | 'hierro'
  | 'magia'
  | 'cielo'
  | 'plata'
  | 'lavanda'
  | 'cajeta'
  | 'wasabi'
  | 'princesa'
  | 'nube';

export type Theme = 'newspaper' | 'candyland' | 'test';

export const allThemes: Theme[] = ['newspaper', 'candyland', 'test'];
